apiVersion: apps/v1
kind: Deployment
metadata:
  name: subsonic
spec:
  replicas: 4
  selector:
   matchLabels:
    app: subsonic
  template:
    metadata:
      labels:
        app: subsonic
    spec:
      containers:
      - name: subsonic
        image: hurricane/subsonic
        env:
         - name: HTTP_PORT
           value: "80"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: subsonic-svc
  labels:
    run: subsonic-svc
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: subsonic
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: subsonic-ingress
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`app.sound-buzz.live`)
      kind: Rule
      services:
        - name: subsonic-svc
          port: 80